import type React from "react"
import "../globals.css"
import { Search } from "lucide-react"
import { Bell } from "lucide-react"
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "./_components/Sidebar"

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <SidebarProvider>
          <div className="flex flex-col md:flex-row min-h-screen w-full">
            <AppSidebar />

            <div className="flex-1 flex flex-col">
              <header className="h-[72px] flex justify-between items-center px-4 bg-white sticky top-0 z-50">
                <div className="flex items-center gap-2">
                  <div className="md:hidden">
                    <SidebarTrigger />
                  </div>

                  <div className="relative w-full max-w-[300px] hidden sm:block">
                    <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-500 h-[18px] pointer-events-none" />
                    <input type="text" placeholder="Search" className="pl-10 p-3 w-full rounded-lg border bg-gray-50" />
                  </div>
                </div>

                <div className="flex items-center gap-3 md:gap-6">
                  {/* Search icon for mobile */}
                  <Search className="w-5 h-5 sm:hidden" />

                  {/* Bell Icon */}
                  <Bell className="w-5 h-5 md:w-6 md:h-6 text-black" />

                  {/* Divider - hidden on small screens */}
                  <div className="hidden md:block w-px h-10 bg-gray-300" />

                  {/* Avatar and User Info */}
                  <div className="flex items-center gap-2 md:gap-4">
                    <div className="relative">
                      <Avatar className="w-8 h-8 md:w-12 md:h-12">
                        <AvatarImage src="https://github.com/rajab.png" alt="Mr. Raja" />
                        <AvatarFallback>MR</AvatarFallback>
                      </Avatar>
                      {/* Online Indicator */}
                      <span className="absolute bottom-0 right-0 w-2 h-2 md:w-3 md:h-3 bg-green-500 border-2 border-white rounded-full" />
                    </div>

                    {/* Text Info - hidden on small screens */}
                    <div className="hidden sm:block">
                      <h2 className="text-base md:text-lg font-semibold">Mr. Raja</h2>
                      <p className="text-xs md:text-sm text-gray-600">Admin</p>
                    </div>
                  </div>
                </div>
              </header>

              <main className="bg-[#eaf6ec] flex-1 p-3 md:p-5">
                <div>{children}</div>
              </main>
            </div>
          </div>
        </SidebarProvider>
      </body>
    </html>
  )
}
