import Sidebar from "./_components/Sidebar";
import "../globals.css";
import { Search } from "lucide-react";
import { Bell } from "lucide-react";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import PathTracker from "./_components/PathTracker";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex">
        <div className=" w-[232px] hidden lg:flex flex-col sticky top-0 h-screen overflow-auto bg-[#ffffff]">
          <Sidebar />
        </div>

        <div className="w-full">
          <div className="h-[72px] flex justify-between items-center px-4 bg-[#ffffff] sticky top-0 z-50">
            <div className="flex flex-col justify-center h-full">
              <div className="relative w-[300px]">
                <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-500 h-[18px] pointer-events-none" />
                <input
                  type="text"
                  placeholder="search"
                  className="pl-10 p-3 w-full rounded-lg"
                />
              </div>
            </div>

            <div className="flex items-center gap-6">
              {/* Bell Icon */}
              <Bell className="w-6 h-6 text-black" />

              {/* Divider */}
              <div className="w-px h-10 bg-gray-300" />

              {/* Avatar and User Info */}
              <div className="flex items-center gap-4">
                <div className="relative">
                  <Avatar className="w-12 h-12">
                    <AvatarImage
                      src="https://github.com/rajab.png"
                      alt="Mr. Raja"
                    />
                    <AvatarFallback>MR</AvatarFallback>
                  </Avatar>
                  {/* Online Indicator */}
                  <span className="absolute bottom-0 right-0 w-3 h-3 bg-green-500 border-2 border-white rounded-full" />
                </div>

                {/* Text Info */}
                <div>
                  <h2 className="text-lg font-semibold">Mr. Raja</h2>
                  <p className="text-sm text-gray-600">Admin</p>
                </div>
              </div>
            </div>
          </div>

          <div className="bg-[#eaf6ec] min-h-screen p-5">
            <PathTracker />

            <div>{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
